### ISSUE TITLE
发现 每日投币 的经验值没有获取

### ISSUE THREAD

**Issue by Jacobax** [srcrs/BilibiliTask#118]
![屏幕截图 2020-12-31 232337](https://user-images.githubusercontent.com/23228895/103416221-b0fb5f00-4bc0-11eb-8b0e-51b83c9cce59.png)

**Comment by srcrs** [comment]
这个是b站的问题，经验实际是增加了的，不用担心的。可以看一下今天的日志里的经验，和你现在的经验比较一下。

**Comment by Jacobax** [comment]
> 这个是b站的问题，经验实际是增加了的，不用担心的。可以看一下今天的日志里的经验，和你现在的经验比较一下。
算了下还真是相差65经验值，谢了

**Comment by Jacobax** [comment]
还有，这每天亏4硬币，直至用完？

**Comment by srcrs** [comment]
> 还有，这每天亏4硬币，直至用完？

可以在`src/main/resources/config.yml`文件中，将`coin`项设置为`0`，每天就不用投币了

**Comment by srcrs** [comment]
> 还有，这每天亏4硬币，直至用完？

如果你不设置就会每天都投，直至用完。

**Comment by Jacobax** [comment]
> > 还有，这每天亏4硬币，直至用完？
> 
> 如果你不设置就会每天都投，直至用完。

不投币领不到那50经验值，还是不改了，反正也没什么用
顺便，元旦快乐

**Comment by srcrs** [comment]
> > > 还有，这每天亏4硬币，直至用完？
> > 
> > 
> > 如果你不设置就会每天都投，直至用完。
> 
> 不投币领不到那50经验值，还是不改了，反正也没什么用
> 顺便，元旦快乐

元旦快乐
