### ISSUE TITLE
关于添加up的UID

### ISSUE THREAD

**Issue by meijianyue** [srcrs/BilibiliTask#134]
为啥我在投币哪里添加了UID不行啊，要以什么的格式添加啊，就添加一个up的话，yml的格式是什么样的

**Comment by meijianyue** [comment]
upList: 29440965       我这样写的不行

**Comment by srcrs** [comment]
> upList: 29440965 我这样写的不行
```yml
upList:
  - 29440965
```
要这样添加，它是一个数组。
