### ISSUE TITLE
希望可以支持多账户登陆

### ISSUE THREAD

**Issue by chh-love-you** [srcrs/BilibiliTask#16]
如题

**Comment by srcrs** [comment]
> 如题

为什么会有这个需求呢？

**Comment by chh-love-you** [comment]
> > 如题
> 
> 为什么会有这个需求呢？

想帮朋友一起签到

**Comment by srcrs** [comment]
> > > 如题
> > 
> > 为什么会有这个需求呢？
> 
> 想帮朋友一起签到

可以让你朋友也注册个github嘛

**Comment by chh-love-you** [comment]
> > > > 如题
> > > 
> > > 
> > > 为什么会有这个需求呢？
> > 
> > 
> > 想帮朋友一起签到
> 
> 可以让你朋友也注册个github嘛

这个朋友是我妹妹，（雾）

**Comment by chh-love-you** [comment]
> > > > 如题
> > > 
> > > 
> > > 为什么会有这个需求呢？
> > 
> > 
> > 想帮朋友一起签到
> 
> 可以让你朋友也注册个github嘛

实在没办法的话就算了吧。

**Comment by chh-love-you** [comment]
> > > > 如题
> > > 
> > > 
> > > 为什么会有这个需求呢？
> > 
> > 
> > 想帮朋友一起签到
> 
> 可以让你朋友也注册个github嘛



> > > > > 如题
> > > > 
> > > > 
> > > > 为什么会有这个需求呢？
> > > 
> > > 
> > > 想帮朋友一起签到
> > 
> > 
> > 可以让你朋友也注册个github嘛
> 
> 这个朋友是我妹妹，（雾）

实在没办法就算了吧，我和她解释一下。

**Comment by srcrs** [comment]
> > > > 如题
> > > 
> > > 为什么会有这个需求呢？
> > 
> > 想帮朋友一起签到
> 
> 可以让你朋友也注册个github嘛

多用户也很好实现，只不过这个操作比较敏感。

**Comment by chh-love-you** [comment]
> > > > > 如题
> > > > 
> > > > 
> > > > 为什么会有这个需求呢？
> > > 
> > > 
> > > 想帮朋友一起签到
> > 
> > 
> > 可以让你朋友也注册个github嘛
> 
> 多用户也很好实现，只不过这个操作比较敏感。

会有风险么？

**Comment by srcrs** [comment]
> > > > > > 如题
> > > > > 
> > > > > 
> > > > > 为什么会有这个需求呢？
> > > > 
> > > > 
> > > > 想帮朋友一起签到
> > > 
> > > 
> > > 可以让你朋友也注册个github嘛
> > 
> > 多用户也很好实现，只不过这个操作比较敏感。
> 
> 会有风险么？

你其实可以自己实现一下，代码逻辑很简单。或者帮你妹妹注册个github，并用server酱每天都推送到她的微信岂不是更好？

**Comment by chh-love-you** [comment]
> > > > > > > 如题
> > > > > > 
> > > > > > 
> > > > > > 为什么会有这个需求呢？
> > > > > 
> > > > > 
> > > > > 想帮朋友一起签到
> > > > 
> > > > 
> > > > 可以让你朋友也注册个github嘛
> > > 
> > > 
> > > 多用户也很好实现，只不过这个操作比较敏感。
> > 
> > 
> > 会有风险么？
> 
> 你其实可以自己实现一下，代码逻辑很简单。或者帮你妹妹注册个github，并用server酱每天都推送到她的微信岂不是更好？

好的谢谢
