### ISSUE TITLE
账号封禁问题

### ISSUE THREAD

**Issue by ZHJ0125** [srcrs/BilibiliTask#19]
请问一下，使用您的代码刷经验的话，会不会被B站封禁账号呢?
或者说有多大的可能会被B站检测到账号异常，导致被封号? 
- [ ] 根本不会被检测到
- [ ] 有很小的可能会被检测到
- [ ] 有很大的可能会被检测到
- [ ] 极有可能被检测到
- [ ] 就算检测到异常, 也不会封禁账号

我没有恶意，只是想了解一下，以免自己被封。

**Comment by srcrs** [comment]
> 请问一下，使用您的代码刷经验的话，会不会被B站封禁账号呢?
> 或者说有多大的可能会被B站检测到账号异常，导致被封号?
> 
> * [ ]  根本不会被检测到
> * [ ]  有很小的可能会被检测到
> * [ ]  有很大的可能会被检测到
> * [ ]  极有可能被检测到
> * [ ]  就算检测到异常, 也不会封禁账号
> 
> 我没有恶意，只是想了解一下，以免自己被封。

封号我觉得应该不用会，因为并没有影响B站的利益，相反还增加了用户的每月活跃度，我们仅仅是自动获取了一些经验，暂时还未听说有被封号的情况。

**Comment by ZHJ0125** [comment]
好的，感谢您的回复👍
感谢您的开源项目🎉

**Comment by srcrs** [comment]
> 感谢您的开源项目

感谢你的关注😄
