### ISSUE TITLE
建议增加企业微信的推送，感谢大佬。

### ISSUE THREAD

**Issue by roc0838** [srcrs/BilibiliTask#195]
"""
大佬，sever酱的普通版本要停止了，故而我自己从网上寻求了一个新的用企业微信的方法，代码如下，不知大佬能否增加一下这个呀qaq,github不会玩。。。。。。感谢大佬。
企业微信的玩法就是：
注册----应用管理----创建应用----就可以得到应用ID( Agentid )，应用Secret( Secret )----我的企业，企业信息最下面就是企业ID.
"""
import os
import json
import time
import requests
"""
python发消息给微信
"""

def send2wechat(AgentId, Secret, CompanyId, message):
"""
:param AgentId: 应用ID
:param Secret: 应用Secret
:param CompanyId: 企业ID
"""
# 通行密钥
ACCESS_TOKEN = None
# 如果本地保存的有通行密钥且时间不超过两小时，就用本地的通行密钥
if os.path.exists('ACCESS_TOKEN.txt'):
txt_last_edit_time = os.stat('ACCESS_TOKEN.txt').st_mtime
now_time = time.time()
print('ACCESS_TOKEN_time:', int(now_time - txt_last_edit_time))
if now_time - txt_last_edit_time < 7200: # 官方说通行密钥2小时刷新
with open('ACCESS_TOKEN.txt', 'r') as f:
ACCESS_TOKEN = f.read()
# print(ACCESS_TOKEN)
# 如果不存在本地通行密钥，通过企业ID和应用Secret获取
if not ACCESS_TOKEN:
r = requests.post(f'https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={CompanyId}&corpsecret={Secret}').json()
ACCESS_TOKEN = r["access_token"]
# print(ACCESS_TOKEN)
# 保存通行密钥到本地ACCESS_TOKEN.txt
with open('ACCESS_TOKEN.txt', 'w', encoding='utf-8') as f:
f.write(ACCESS_TOKEN)
# 要发送的信息格式
data = {
"touser": "@ALL",
"msgtype": "text",
"agentid": f"{AgentId}",
"text": {"content": f"{message}"}
}
# 字典转成json，不然会报错
data = json.dumps(data)
# 发送消息
r = requests.post(f'https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={ACCESS_TOKEN}', data=data)
# print(r.json())

if name == 'main':
# 应用ID
AgentId_ = '100000x'
# 应用Secret
Secret_ = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
# 企业ID
CompanyId_ = 'xxxxxxxxxxxxxxxxxx'
# 发送的消息
message_ = '你好，wechat！'
send2wechat(AgentId_, Secret_, CompanyId_, message_)

**Comment by srcrs** [comment]
好的，有时间会增加的
