### ISSUE TITLE
模拟观看视频 分享视频投币失败

### ISSUE THREAD

**Issue by ylrepertory** [srcrs/BilibiliTask#21]
接口调用显示msg显示“csrf 校验失败” 这是为啥？

**Comment by srcrs** [comment]
> 接口调用显示msg显示“csrf 校验失败” 这是为啥？

建议你再重新在Secrets中填写SESSDATA，bili_jct，DedeUserID这三个参数，出现“csrf校验失败”是因为bili_jct无效

**Comment by ylrepertory** [comment]
需要重新登录获取吗？我是直接在启动代码的时候添加参数的 ，没有用github的action。check已经调用通过，用户信息已经拿到。调用分享接口返回异常

**Comment by srcrs** [comment]
> 需要重新登录获取吗？我是直接在启动代码的时候添加参数的 ，没有用github的action。check已经调用通过，用户信息已经拿到。调用分享接口返回异常

啊，这样啊。那你需要注意一下参数的顺序 
bili_jct SESSDATA DedeUserID
按照这个顺序，用空格间隔

**Comment by ylrepertory** [comment]
嗯嗯 已经找到了
