### ISSUE TITLE
建议加上免费的B币卷兑换金瓜子的功能

### ISSUE THREAD

**Issue by fengpan0403** [srcrs/BilibiliTask#26]

**Comment by srcrs** [comment]
暂时使用的是B币卷给自己充电。不过也可以考虑增加一个B币卷兑换金瓜子的功能，可是该在什么时候兑换呢？

**Comment by fengpan0403** [comment]
我觉得autoCharge配置里如果是false就换金瓜子吧，反正留着也是过期了，不用白不用，这币必须得花了~

**Comment by srcrs** [comment]
> 我觉得autoCharge配置里如果是false就换金瓜子吧，反正留着也是过期了，不用白不用，这币必须得花了~

是的，那我一会给加上吧，添加一个配置项。

**Comment by srcrs** [comment]
你会抓接口吗，我这边不是年度大会员没法测试

**Comment by huanzhou-sama** [comment]
为啥我的银瓜子没增加过😭

**Comment by srcrs** [comment]
> 为啥我的银瓜子没增加过😭

我也好久每增加过了😭

**Comment by srcrs** [comment]
> 为啥我的银瓜子没增加过😭

每个月好像有两天是礼物签到，会送666银瓜子，或者辣条50个

**Comment by huanzhou-sama** [comment]
> > 为啥我的银瓜子没增加过😭
> 
> 每个月好像有两天是礼物签到，会送666银瓜子，或者辣条50个

好的🤣🤣，还有就是那个 拉取最新代码的那段教程没看懂(萌新)😭

**Comment by srcrs** [comment]
> > > 为啥我的银瓜子没增加过😭
> > 
> > 
> > 每个月好像有两天是礼物签到，会送666银瓜子，或者辣条50个
> 
> 好的🤣🤣，还有就是那个 拉取最新代码的那段教程没看懂(萌新)😭

你会把仓库克隆到本地吗？

**Comment by fengpan0403** [comment]
[capture.zip](https://github.com/srcrs/BilibiliTask/files/5476145/capture.zip)
我的B币之前兑换完了，用fiddler抓了个失败的包，不过感觉应该可以用。

**Comment by srcrs** [comment]
> [capture.zip](https://github.com/srcrs/BilibiliTask/files/5476145/capture.zip)
> 我的B币之前兑换完了，用fiddler抓了个失败的包，不过感觉应该可以用。

好的，感谢

**Comment by srcrs** [comment]
> [capture.zip](https://github.com/srcrs/BilibiliTask/files/5476145/capture.zip)
> 我的B币之前兑换完了，用fiddler抓了个失败的包，不过感觉应该可以用。

已增加B币兑换金瓜子，更新到最新代码，修改 autoBCoin 配置项为 2 即可

**Comment by huanzhou-sama** [comment]
> > > > 为啥我的银瓜子没增加过😭
> > > 
> > > 
> > > 每个月好像有两天是礼物签到，会送666银瓜子，或者辣条50个
> > 
> > 好的🤣🤣，还有就是那个 拉取最新代码的那段教程没看懂(萌新)😭
> 
> 你会把仓库克隆到本地吗？

等学了git我再来🙊

**Comment by srcrs** [comment]
> > > > > 为啥我的银瓜子没增加过😭
> > > > 
> > > > 
> > > > 每个月好像有两天是礼物签到，会送666银瓜子，或者辣条50个
> > > 
> > > 
> > > 好的🤣🤣，还有就是那个 拉取最新代码的那段教程没看懂(萌新)😭
> > 
> > 
> > 你会把仓库克隆到本地吗？
> 
> 等学了git我再来🙊

好的😄

**Comment by happy888888** [comment]
B币(劵)兑换金瓜子接口为`https://api.live.bilibili.com/xlive/revenue/v1/order/createOrder`
请求方式post，application/x-www-form-urlencoded，字段如下

| 字段                            | 类型    | 内容                           | 备注                                                         |
| ------------------------------- | ------- | ------------------------------ | ------------------------------------------------------------ |
| platform                            | str     | 平台                       |  可填"pc"                                                            |
| pay_bp                             | num     | 稿件avID                       | 兑换瓜子数量                                                             |
| context_id                          | num     | 未知                    | 可填1                                                      |
| context_type                             | num     | 未知                        |  可填11                                                            |
| goods_id                           | num     | 商品id                     |  可填1                                                            |
| goods_num                       | num     | 商品数量                       | 花费B币(劵)数量                                         |
| csrf                             | str     | csrf                |  来自cookie                                                            |
| csrf_token                           | str     | 同上                       |  同上(可选)                                                            |
| visit_id                         | num     | 身份id                   | 来自商店页面(可选)                                                       |

返回失败和成功示例如下
```
{"code":1300014,"message":"b币余额不足","ttl":1,"data":null}
{"code":0,"message":"0","ttl":1,"data":{"status":2,"order_id":"2011042258413961167422787","gold":0,"bp":0}}
```

`order_id`为购买订单编号

**Comment by srcrs** [comment]
> B币(劵)兑换金瓜子接口为`https://api.live.bilibili.com/xlive/revenue/v1/order/createOrder`
> 请求方式post，application/x-www-form-urlencoded，字段如下
> 
> 字段	类型	内容	备注
> platform	str	平台	可填"pc"
> pay_bp	num	稿件avID	兑换瓜子数量
> context_id	num	未知	可填1
> context_type	num	未知	可填11
> goods_id	num	商品id	可填1
> goods_num	num	商品数量	花费B币(劵)数量
> csrf	str	csrf	来自cookie
> csrf_token	str	同上	同上(可选)
> visit_id	num	身份id	来自商店页面(可选)
> 返回失败和成功示例如下
> 
> ```
> {"code":1300014,"message":"b币余额不足","ttl":1,"data":null}
> {"code":0,"message":"0","ttl":1,"data":{"status":2,"order_id":"2011042258413961167422787","gold":0,"bp":0}}
> ```
> 
> `order_id`为购买订单编号

感谢😄，我充了一个B币已经拿到结果了。
