### ISSUE TITLE
投币后不涨经验

### ISSUE THREAD

**Issue by GENEVE0086** [srcrs/BilibiliTask#29]
如题所述，有可能是阿b方面发现问题之后加了屏蔽嘛？
以下为相关截图
投币记录：
<img width="442" alt="image" src="https://user-images.githubusercontent.com/34123867/98237449-d9d7ed00-1f9f-11eb-8fb5-465f86762a0f.png">
经验详情：
<img width="233" alt="image" src="https://user-images.githubusercontent.com/34123867/98237492-eeb48080-1f9f-11eb-971d-97253e8077e0.png">

**Comment by srcrs** [comment]
> 如题所述，有可能是阿b方面发现问题之后加了屏蔽嘛？
> 以下为相关截图
> 投币记录：
> <img alt="image" width="442" src="https://user-images.githubusercontent.com/34123867/98237449-d9d7ed00-1f9f-11eb-8fb5-465f86762a0f.png">
> 经验详情：
> <img alt="image" width="233" src="https://user-images.githubusercontent.com/34123867/98237492-eeb48080-1f9f-11eb-971d-97253e8077e0.png">

这个不用担心的，有投币就会有经验。这个属于哔哩哔哩的问题，每日投币所获得的经验有时候会显示错误，我也有时候会出现这样的问题。你可以看一下日志，你投币前的经验是多少，看看经验是否有增加。

**Comment by huanzhou-sama** [comment]
> 如题所述，有可能是阿b方面发现问题之后加了屏蔽嘛？
> 以下为相关截图
> 投币记录：
> <img width="442" alt="image" src="https://user-images.githubusercontent.com/34123867/98237449-d9d7ed00-1f9f-11eb-8fb5-465f86762a0f.png">
> 经验详情：
> <img width="233" alt="image" src="https://user-images.githubusercontent.com/34123867/98237492-eeb48080-1f9f-11eb-971d-97253e8077e0.png">
> 

![-5d7f34ecac404fda.png](https://user-images.githubusercontent.com/72246051/98238319-2ec83300-1fa1-11eb-9508-05e19d9d8d67.png)
可能是延迟问题，反正我的没问题

**Comment by srcrs** [comment]
晚点看一下估计就好了，以前我正常投币都有时候不显示投币所获得的经验，过段时间刷新又好了。

**Comment by ZHJ0125** [comment]
✔ 确实是B站有延时，我的每日经验显示没加经验，但实际上在经验记录里已经给经验了。
![每日经验](https://user-images.githubusercontent.com/34802690/98671295-ffde0280-238e-11eb-9037-e0e67ab8d420.png)

✔ 可以去[经验记录页面](https://account.bilibili.com/account/record)里查看详细信息👇
![经验记录](https://user-images.githubusercontent.com/34802690/98671543-6531f380-238f-11eb-91ac-31035331adb9.png)

✔ 放心，本项目没问题的。
