### ISSUE TITLE
其实可以把action单独成一个仓库

### ISSUE THREAD

**Issue by linsongze** [srcrs/BilibiliTask#31]
单独一个action仓库，然后在里面执行git clone你最新源码的这个仓库，来进行编译执行的操作，这样可以省去fork了这个仓库之后，没来得及同步最新源码的情况。

**Comment by srcrs** [comment]
> 单独一个action仓库，然后在里面执行git clone你最新源码的这个仓库，来进行编译执行的操作，这样可以省去fork了这个仓库之后，没来得及同步最新源码的情况。

但如果这样的话，用户的自定义配置信息可能会覆盖。投币啊，自动送出即将过期礼物等等不能自定义配置。

**Comment by linsongze** [comment]
可以的，自定义信息你是放配置文件的，在action仓库也放这个配置信息的yml文件，在action描述文件里面用Run 
 shell在git clone 完成之后替换掉源码里面的，然后再mvn编译执行就行了

**Comment by happy888888** [comment]
这个方法我在 [JunzhouLiu/BILIBILI-HELPER](https://github.com/JunzhouLiu/BILIBILI-HELPER) 的一次 [pull requests](https://github.com/JunzhouLiu/BILIBILI-HELPER/pull/6#issuecomment-708443781) 中讨论用户更新代码的方法时提到过，不过并没有被采纳。

我认为应该将用户配置文件设为外部资源文件(src文件夹是内部资源，用户配置文件在程序内部就没有意义了，~~见过哪个win程序的用户配置是放在exe文件内部的~~)，每次执行actions时直接拉取源代码仓库(或者在release里发布jar包省去每次编译)执行就行。用户配置文件放在新仓库或者secrets里运行时动态释放到指定位置就行了。

然后主要问题就是保证以后的新版本必须兼容旧版本的配置文件了。

**Comment by srcrs** [comment]
我觉得还是不太可靠。每个版本的代码和配置文件都最好要相匹配，因为很难保证新版本兼容旧版本配置文件（代码写的烂），尤其也是没想好在未来到底哪些东西应该让用户去自定义配置。
其实每个版本基础的功能都差不多，没必要都使用最新代码。或者使用happy老哥的自动拉取更新的actions，就很好了。
