### ISSUE TITLE
B币券不支持小数

### ISSUE THREAD

**Issue by Lovestarni** [srcrs/BilibiliTask#35]
使用B币卷部分异常 -- java.lang.NumberFormatException: For input string: "2.5"

**Comment by srcrs** [comment]
> 使用B币卷部分异常 -- java.lang.NumberFormatException: For input string: "2.5"

B币卷还有小数？😂

**Comment by srcrs** [comment]
> 使用B币卷部分异常 -- java.lang.NumberFormatException: For input string: "2.5"

好的，马上解决。

**Comment by Lovestarni** [comment]
有的，我刚好花的还剩2.5b币券，然后就报错了😂
