### ISSUE TITLE
通知方式能否支持更多方式例如钉钉

### ISSUE THREAD

**Issue by dcdlove** [srcrs/BilibiliTask#37]
配置项 增加配置通知方式选择微信或者钉钉

**Comment by srcrs** [comment]
> 配置项 增加配置通知方式选择微信或者钉钉

可以搞一个钉钉推送。你有什么好的思路吗，或者丢一个文档也行。我在网上看到可以通过钉钉群机器人实现。

**Comment by CaoMeiYouRen** [comment]
> > 配置项 增加配置通知方式选择微信或者钉钉
> 
> 可以搞一个钉钉推送。你有什么好的思路吗，或者丢一个文档也行。我在网上看到可以通过钉钉群机器人实现。

机器人是可以的。实际上采用webhook应该能解决问题。通知时向指定地址发一个请求就行了

**Comment by 710961349** [comment]
那还不如直接邮件推送就好了

**Comment by srcrs** [comment]
> 那还不如直接邮件推送就好了

邮件也是可以的，等段时间再说吧😂。

**Comment by srcrs** [comment]
> 配置项 增加配置通知方式选择微信或者钉钉

已经支持推送到钉钉
