### ISSUE TITLE
关于投币对象

### ISSUE THREAD

**Issue by loststar** [srcrs/BilibiliTask#38]
能否优先投币给关注的人？

**Comment by srcrs** [comment]
> 能否优先投币给关注的人？

其实我感觉只要币能投出去就行了😂，既然你有这样的需求，那我就抽空更新一下吧。

**Comment by hupo376787** [comment]
是的，给某个人投币，或者可以有个配置文件自己定义

**Comment by srcrs** [comment]
> 是的，给某个人投币，或者可以有个配置文件自己定义

1.我准备把投币策略改成这样：每次从自己的动态列表获取前20个视频（已经关注的up主发布的最新会在这里出现），从中挑选未投币的视频进行投币，如果未能达到配置文件中每日投币的数量，就从热门视频中挑选视频进行补充投币。
2.增加给某个人投币，也是可以实现的。但是问题来了，是给该up主所有发布的视频都投币，还是说只给他发布最新的视频投币？

**Comment by hupo376787** [comment]
第一个策略很好
第二个我觉得给最新的视频投币即可😂

谢谢大佬的repo

**Comment by srcrs** [comment]
> 第一个策略很好
> 第二个我觉得给最新的视频投币即可😂
> 
> 谢谢大佬的repo
> 

可以，那到时候优先级为: 配置文件up主最新视频>自己的动态列表视频>随机热门视频

**Comment by hupo376787** [comment]
好，这样就符合题主的提问了，把币优先投给自己关注/认识的人。

谢谢

**Comment by srcrs** [comment]
> 能否优先投币给关注的人？

已增加优先投币给关注的up，还可以指定优先投币给哪个up

**Comment by srcrs** [comment]
> 是的，给某个人投币，或者可以有个配置文件自己定义

老铁，更新试一试啊
