### ISSUE TITLE
yml 数据形式的疑问

### ISSUE THREAD

**Issue by 710961349** [srcrs/BilibiliTask#39]
是这样的形式吗？
``` yml
upList: 
  - XXXX
  - XXXX         # 自定义优先给这些 up 的视频投币 , 以yml数组的形式 , 填写其 uid (mid)
```

**Comment by srcrs** [comment]
> 是这样的形式吗？
> ``` yml
> upList: 
>   - XXXX
>   - XXXX         # 自定义优先给这些 up 的视频投币 , 以yml数组的形式 , 填写其 uid (mid)
> ```

对的，是这样的
