### ISSUE TITLE
post参数问题

### ISSUE THREAD

**Issue by happy888888** [srcrs/BilibiliTask#4]
[Function.java](https://github.com/srcrs/BilibiliTask/blob/f809181c1b202263cca4966af9011d169bb129d1/src/main/java/org/example/Function.java#L492) 这里及下面的三个方法中post的类型不是"[application/x-www-form-urlencoded](https://github.com/srcrs/BilibiliTask/blob/f809181c1b202263cca4966af9011d169bb129d1/src/main/java/org/example/Request.java#L67)"而是"application/json"，body应该是{"param1":"key1","param2":"key2"}格式的而不是"param1=key1&param2=key2"格式的。

事实上大部分app的接口都用的json格式提交，而不是浏览器接口的x-www-form-urlencoded格式，可以重载一个post方法用于json格式数据的提交

**Comment by srcrs** [comment]
> [Function.java](https://github.com/srcrs/BilibiliTask/blob/f809181c1b202263cca4966af9011d169bb129d1/src/main/java/org/example/Function.java#L492)此处及以下的三个方法中post的类型不是“ [application / x-www-form-urlencoded](https://github.com/srcrs/BilibiliTask/blob/f809181c1b202263cca4966af9011d169bb129d1/src/main/java/org/example/Request.java#L67) ”另外“ application / json”，body应该是{“ param1”：“ key1”，“ param2”： “ key2”}格式的而不是“ param1 = key1＆param2 = key2”格式的。
> 
> 实际上大部分应用的接口都用的json格式提交，而不是浏览器接口的x-www-form-urlencoded格式，可以重载一个帖子方法用于json格式数据的提交

我以前也是准备用json格式提交请求的，但是当我把post请求封装成application / json，body是{“ param1”：“ key1”，“ param2”： “ key2”}形式，请求就会爆出“请求错误”，要么是参数错误。后来我换成现在这种形式就正常了，我也很迷惑。按讲说json格式是最正规的，我这不知道为什么不行。*_*

**Comment by happy888888** [comment]
这个请求错误是java抛出的异常还是服务器返回的错误，httpcode是多少

**Comment by srcrs** [comment]
是服务器的，例如share那个请求会爆出
```json
{"code":-400,"message":"请求错误","ttl":1}
```




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "星辰"<notifications@github.com&gt;; 
发送时间: 2020年10月10日(星期六) 下午2:02
收件人: "srcrs/BilibiliTask"<BilibiliTask@noreply.github.com&gt;; 
抄送: "srcrs"<srcrs@foxmail.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [srcrs/BilibiliTask] post参数问题 (#4)





 
这个请求错误是java抛出的异常还是服务器返回的错误，httpcode是多少

**Comment by happy888888** [comment]
只有app端的接口用json格式提交，share那个接口是web端的不用改

**Comment by srcrs** [comment]
啊，好的

**Comment by happy888888** [comment]
post与get不是可以设置为静态方法吗，每次都new一个request感觉浪费开销了，inputStream不close不知道会不会影响HttpURLConnection的底层套接字复用啊。

**Comment by srcrs** [comment]
确实，有点浪费内存，我开始就是想模仿模仿 python，一些框架的写法，一会把对象改成单例的算了。inputStream貌似不会自动关闭我添加一个关闭吧。谢谢指导




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "srcrs/BilibiliTask"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 下午5:38
收件人:&nbsp;"srcrs/BilibiliTask"<BilibiliTask@noreply.github.com&gt;;
抄送:&nbsp;"srcrs"<srcrs@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [srcrs/BilibiliTask] post参数问题 (#4)





 
post与get不是可以设置为静态方法吗，每次都new一个request感觉浪费开销了，inputStream不close不知道会不会影响HttpURLConnection的底层套接字复用啊。
