### ISSUE TITLE
功能的其他部分如何设置，直播签到和漫画签到如何设置和关闭

### ISSUE THREAD

**Issue by Drapho** [srcrs/BilibiliTask#40]
请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？

**Comment by srcrs** [comment]
> 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？

1.直播签到反正也不耗费什么东西，签到也没事吧。
2.暂时不支持自定义看谁的直播(无法直播挂机)
3.漫画签到也无所谓，也不要耗费什么东西😃

**Comment by Drapho** [comment]
> > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> 
> 1.直播签到反正也不耗费什么东西，签到也没事吧。
> 2.暂时不支持自定义看谁的直播(无法直播挂机)
> 3.漫画签到也无所谓，也不要耗费什么东西😃

哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了

**Comment by srcrs** [comment]
> > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > 
> > 
> > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > 3.漫画签到也无所谓，也不要耗费什么东西😃
> 
> 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了

可以，那我一会给漫画签到弄个开关。

**Comment by Drapho** [comment]
> > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > 
> > > 
> > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > 
> > 
> > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> 
> 可以，那我一会给漫画签到弄个开关。

谢谢！！！！！！辛苦啦！！！！！！

**Comment by srcrs** [comment]
> > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > 
> > > > 
> > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > 
> > > 
> > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > 
> > 
> > 可以，那我一会给漫画签到弄个开关。
> 
> 谢谢！！！！！！辛苦啦！！！！！！

已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可

**Comment by Drapho** [comment]
> > > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > > 
> > > > > 
> > > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > > 
> > > > 
> > > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > > 
> > > 
> > > 可以，那我一会给漫画签到弄个开关。
> > 
> > 
> > 谢谢！！！！！！辛苦啦！！！！！！
> 
> 已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可

好嘞！谢谢！！

**Comment by Drapho** [comment]
> > > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > > 
> > > > > 
> > > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > > 
> > > > 
> > > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > > 
> > > 
> > > 可以，那我一会给漫画签到弄个开关。
> > 
> > 
> > 谢谢！！！！！！辛苦啦！！！！！！
> 
> 已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可

小白不会更新代码QAQ，不下软件是不是更新不了呀

**Comment by Drapho** [comment]
> > > > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > > > 
> > > > > > 
> > > > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > > > 
> > > > > 
> > > > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > > > 
> > > > 
> > > > 可以，那我一会给漫画签到弄个开关。
> > > 
> > > 
> > > 谢谢！！！！！！辛苦啦！！！！！！
> > 
> > 
> > 已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可
> 
> 小白不会更新代码QAQ，不下软件是不是更新不了呀

好像有点弄明白了QAQ

**Comment by Drapho** [comment]
> > > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > > 
> > > > > 
> > > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > > 
> > > > 
> > > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > > 
> > > 
> > > 可以，那我一会给漫画签到弄个开关。
> > 
> > 
> > 谢谢！！！！！！辛苦啦！！！！！！
> 
> 已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可

This branch has conflicts that must be resolved
Use the command line to resolve conflicts before continuing.
Conflicting files
src/main/resources/config.yml

网页更新提示这个，是不是无视掉就好了呀~

**Comment by srcrs** [comment]
> > > > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > > > 
> > > > > > 
> > > > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > > > 
> > > > > 
> > > > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > > > 
> > > > 
> > > > 可以，那我一会给漫画签到弄个开关。
> > > 
> > > 
> > > 谢谢！！！！！！辛苦啦！！！！！！
> > 
> > 
> > 已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可
> 
> This branch has conflicts that must be resolved
> Use the command line to resolve conflicts before continuing.
> Conflicting files
> src/main/resources/config.yml
> 
> 网页更新提示这个，是不是无视掉就好了呀~

这是有分支冲突了，需要解决后才能合并不了。你要不会解决，删除仓库，在重新fork就好了。

**Comment by Drapho** [comment]
> > > > > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > > > > 
> > > > > > > 
> > > > > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > > > > 
> > > > > > 
> > > > > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > > > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > > > > 
> > > > > 
> > > > > 可以，那我一会给漫画签到弄个开关。
> > > > 
> > > > 
> > > > 谢谢！！！！！！辛苦啦！！！！！！
> > > 
> > > 
> > > 已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可
> > 
> > 
> > This branch has conflicts that must be resolved
> > Use the command line to resolve conflicts before continuing.
> > Conflicting files
> > src/main/resources/config.yml
> > 网页更新提示这个，是不是无视掉就好了呀~
> 
> 这是有分支冲突了，需要解决后才能合并不了。你要不会解决，删除仓库，在重新fork就好了。

哦哦，不会解决emm那我删了重弄QAQ不过如果冲突了要怎么解决呢（我想学习一下）

**Comment by srcrs** [comment]
> > > > > > > > > 请问功能中的直播签到，有没有地方设置看谁的直播呢？还有漫画辅助脚本如何设置关闭呢？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 1.直播签到反正也不耗费什么东西，签到也没事吧。
> > > > > > > > 2.暂时不支持自定义看谁的直播(无法直播挂机)
> > > > > > > > 3.漫画签到也无所谓，也不要耗费什么东西😃
> > > > > > > 
> > > > > > > 
> > > > > > > 哦哦我不太看直播，所以之前以为直播签到是对应up主签到hhh直播签到不用开关啦~
> > > > > > > 漫画签到是想关了，因为本身不用bilibili漫画，一般新用户和长时间不用是有阅读卷福利，所以打算想用漫画时再弄哈哈，如果能加个开关就太棒了
> > > > > > 
> > > > > > 
> > > > > > 可以，那我一会给漫画签到弄个开关。
> > > > > 
> > > > > 
> > > > > 谢谢！！！！！！辛苦啦！！！！！！
> > > > 
> > > > 
> > > > 已经可以了，拉去最新代码，在`config.yml`中配置`manga`为`false`即可
> > > 
> > > 
> > > This branch has conflicts that must be resolved
> > > Use the command line to resolve conflicts before continuing.
> > > Conflicting files
> > > src/main/resources/config.yml
> > > 网页更新提示这个，是不是无视掉就好了呀~
> > 
> > 
> > 这是有分支冲突了，需要解决后才能合并不了。你要不会解决，删除仓库，在重新fork就好了。
> 
> 哦哦，不会解决emm那我删了重弄QAQ不过如果冲突了要怎么解决呢（我想学习一下）

你参考一下这篇文章吧， https://blog.csdn.net/yangchunshang/article/details/80281699 ，你需要把用git把仓库拉取到本地处理
