### ISSUE TITLE
直播小礼物相关

### ISSUE THREAD

**Issue by windorz9** [srcrs/BilibiliTask#42]
既然出了优先投币对象, 那么是否后期会加上直播小礼物优先赠送.(垃圾佬续粉丝牌)

**Comment by srcrs** [comment]
> 既然出了优先投币对象, 那么是否后期会加上直播小礼物优先赠送.(垃圾佬续粉丝牌)

可以的。那在配置文件中是设置用户的uid号(间接寻找其直播间id)，还是设置该用户的直播间id，你觉得哪点比较好一点？

**Comment by Drapho** [comment]
> > 既然出了优先投币对象, 那么是否后期会加上直播小礼物优先赠送.(垃圾佬续粉丝牌)
> 
> 可以的。那在配置文件中是设置用户的uid号(间接寻找其直播间id)，还是设置该用户的直播间id，你觉得哪点比较好一点？

感觉UID比较简洁明了→_→

**Comment by windorz9** [comment]
> > 既然出了优先投币对象, 那么是否后期会加上直播小礼物优先赠送.(垃圾佬续粉丝牌)
> 
> 可以的。那在配置文件中是设置用户的uid号(间接寻找其直播间id)，还是设置该用户的直播间id，你觉得哪点比较好一点？

我觉得两种都可以,但是既然优先投币设置使用了 UID, 那这里也直接采用 UID 应该比较合理点. 💪加油.挺不错的项目

**Comment by srcrs** [comment]
> 既然出了优先投币对象, 那么是否后期会加上直播小礼物优先赠送.(垃圾佬续粉丝牌)

可以的。可以通过

> 既然出了优先投币对象, 那么是否后期会加上直播小礼物优先赠送.(垃圾佬续粉丝牌)

已经支持了，更新到最新代码即可。

**Comment by windorz9** [comment]
ok, good.
