### ISSUE TITLE
B 币卷相关

### ISSUE THREAD

**Issue by windorz9** [srcrs/BilibiliTask#43]
看到 Close issues 里面有个B币换金瓜子的 issue, 那么问题来了 b 站每个月月底月初有战友日活动, 一般都是月底最后两天和月初最开始三天, 可以用 5 b币换 15 张漫画福利卷和无门槛会员购优惠券和大会员代金券.是否考虑支持下.

**Comment by srcrs** [comment]
> 看到 Close issues 里面有个B币换金瓜子的 issue, 那么问题来了 b 站每个月月底月初有战友日活动, 一般都是月底最后两天和月初最开始三天, 可以用 5 b币换 15 张漫画福利卷和无门槛会员购优惠券和大会员代金券.是否考虑支持下. 

这个我先了解了解再说吧😂，我不是大会员，对于一些相关活动也不是太了解。

**Comment by windorz9** [comment]
行吧 233
