### ISSUE TITLE
希望支持多个B站账号

### ISSUE THREAD

**Issue by jackforlit** [srcrs/BilibiliTask#47]
希望可以同时运行多个B站账号☺

**Comment by srcrs** [comment]
> 希望可以同时运行多个B站账号☺

为了防止滥用，本项目不支持多用户。抱歉😂。你可采取别的方式实现多用户，例如多个github账号。

**Comment by jackforlit** [comment]
> > 希望可以同时运行多个B站账号☺
> 
> 为了防止滥用，本项目不支持多用户。抱歉😂。你可采取别的方式实现多用户，例如多个github账号。

OK
