### ISSUE TITLE
设置投币对象后，运行任务出错。

### ISSUE THREAD

**Issue by jackforlit** [srcrs/BilibiliTask#50]
出错信息如下：

2020-11-25 16:37:02.406 [INFO ] t.s.u.ReadConfig:27 💔配置文件转换成对象出错 : 
org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=upList for JavaBean=top.srcrs.domain.Config@71423665
 in 'reader', line 2, column 1:
    coin: 5
    ^
No single argument constructor found for interface java.util.List : null
 in 'reader', line 12, column 9:
    upList: *****
            ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:290)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at top.srcrs.util.ReadConfig.transformation(ReadConfig.java:25)
	at top.srcrs.BiliStart.main(BiliStart.java:35)
Caused by: org.yaml.snakeyaml.error.YAMLException: No single argument constructor found for interface java.util.List : null
	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:392)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:267)
	... 10 common frames omitted

**Comment by srcrs** [comment]
> 出错信息如下：
> 
> 2020-11-25 16:37:02.406 [INFO ] t.s.u.ReadConfig:27 💔配置文件转换成对象出错 : 
> org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=upList for JavaBean=top.srcrs.domain.Config@71423665
>  in 'reader', line 2, column 1:
>     coin: 5
>     ^
> No single argument constructor found for interface java.util.List : null
>  in 'reader', line 12, column 9:
>     upList: *****
>             ^
> 
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:290)
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171)
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
> 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
> 	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
> 	at top.srcrs.util.ReadConfig.transformation(ReadConfig.java:25)
> 	at top.srcrs.BiliStart.main(BiliStart.java:35)
> Caused by: org.yaml.snakeyaml.error.YAMLException: No single argument constructor found for interface java.util.List : null
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:392)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:267)
> 	... 10 common frames omitted

配置投币对象填写成这样
`
upList:
  - xxxxxxxx
  - xxxxxxxx
  - xxxxxxxx
`
格式填成这样的

**Comment by srcrs** [comment]
> 出错信息如下：
> 
> 2020-11-25 16:37:02.406 [INFO ] t.s.u.ReadConfig:27 💔配置文件转换成对象出错 : 
> org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=upList for JavaBean=top.srcrs.domain.Config@71423665
>  in 'reader', line 2, column 1:
>     coin: 5
>     ^
> No single argument constructor found for interface java.util.List : null
>  in 'reader', line 12, column 9:
>     upList: *****
>             ^
> 
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:290)
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171)
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
> 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
> 	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
> 	at top.srcrs.util.ReadConfig.transformation(ReadConfig.java:25)
> 	at top.srcrs.BiliStart.main(BiliStart.java:35)
> Caused by: org.yaml.snakeyaml.error.YAMLException: No single argument constructor found for interface java.util.List : null
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:392)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:267)
> 	... 10 common frames omitted

看一下配置文件的例子

**Comment by jackforlit** [comment]
> > 出错信息如下：
> > 2020-11-25 16:37:02.406 [INFO ] t.s.u.ReadConfig:27 💔配置文件转换成对象出错 :
> > org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=upList for JavaBean=top.srcrs.domain.Config@71423665
> > in 'reader', line 2, column 1:
> > coin: 5
> > ^
> > No single argument constructor found for interface java.util.List : null
> > in 'reader', line 12, column 9:
> > upList: *****
> > ^
> > at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:290)
> > at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171)
> > at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
> > at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
> > at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
> > at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
> > at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
> > at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
> > at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
> > at top.srcrs.util.ReadConfig.transformation(ReadConfig.java:25)
> > at top.srcrs.BiliStart.main(BiliStart.java:35)
> > Caused by: org.yaml.snakeyaml.error.YAMLException: No single argument constructor found for interface java.util.List : null
> > at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:392)
> > at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
> > at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
> > at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:267)
> > ... 10 common frames omitted
> 
> 看一下配置文件的例子

我疏忽了。。。。文档没看仔细。
