### ISSUE TITLE
钉钉推送问题

### ISSUE THREAD

**Issue by lancer-wang** [srcrs/BilibiliTask#53]
![image](https://user-images.githubusercontent.com/69783837/100342064-606c7100-3018-11eb-951e-2abfb456d1c5.png)

**Comment by srcrs** [comment]
缺少关键词，在创建机器人时，可以填Task为关键词

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/100405320-54c38d80-309e-11eb-98c9-ce2a0bb0b8fd.png)
测了很久,好像并不是关键词的问题
![image](https://user-images.githubusercontent.com/69783837/100405824-5f325700-309f-11eb-95e0-4ab9cd220326.png)
应该是addParameters传的数据不是json格式的问题
我对java不太懂 不知道有其他什么传递数据的方式

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/100406219-57bf7d80-30a0-11eb-9396-7b57d2803602.png)
我用php测了一下,如果是关键词的话,报的应该是这个错

**Comment by srcrs** [comment]
> ![image](https://user-images.githubusercontent.com/69783837/100406219-57bf7d80-30a0-11eb-9396-7b57d2803602.png)
> 我用php测了一下,如果是关键词的话,报的应该是这个错
> {"errcode":310000,"errmsg":"keywords not in content, more: [https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq]"}

是的，看了下官方文档，https://ding-doc.dingtalk.com/doc?spm=a1zb9.8233112.0.0.340c3a88sgMlJJ#/serverapi2/qf2nxq/9e91d73c ，好像并未有此错误，我稍后回去看一下。

**Comment by srcrs** [comment]
> ![image](https://user-images.githubusercontent.com/69783837/100405320-54c38d80-309e-11eb-98c9-ce2a0bb0b8fd.png)
> 测了很久,好像并不是关键词的问题
> ![image](https://user-images.githubusercontent.com/69783837/100405824-5f325700-309f-11eb-95e0-4ab9cd220326.png)
> 应该是addParameters传的数据不是json格式的问题
> 我对java不太懂 不知道有其他什么传递数据的方式

好的，我稍后回去看一下。

**Comment by srcrs** [comment]
> ![image](https://user-images.githubusercontent.com/69783837/100405320-54c38d80-309e-11eb-98c9-ce2a0bb0b8fd.png)
> 测了很久,好像并不是关键词的问题
> ![image](https://user-images.githubusercontent.com/69783837/100405824-5f325700-309f-11eb-95e0-4ab9cd220326.png)
> 应该是addParameters传的数据不是json格式的问题
> 我对java不太懂 不知道有其他什么传递数据的方式

确实是因为携带参数格式的错误，已经修复，更新到最新代码即可。

**Comment by lancer-wang** [comment]
确认已正常
