### ISSUE TITLE
确认抓包的cookies正常，账户失效？

### ISSUE THREAD

**Issue by 573462273** [srcrs/BilibiliTask#54]
![image](https://user-images.githubusercontent.com/25251970/100479862-70747580-312a-11eb-805c-362d04d07ef8.png)

**Comment by srcrs** [comment]
> ![image](https://user-images.githubusercontent.com/25251970/100479862-70747580-312a-11eb-805c-362d04d07ef8.png)
> 

应该是触发风控了，我一会更新下代码，解决下这个问题。

**Comment by 573462273** [comment]
建议多配置几个有效的Cookies内容

发自我的iPhone

**Comment by srcrs** [comment]
> 建议多配置几个有效的Cookies内容 发自我的iPhone
> […](#)
> 在 2020年11月28日，09:01，srcrs ***@***.***> 写道： ﻿ 应该是触发风控了，我一会更新下代码，解决下这个问题。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我直接把UA给去掉了😂，也可以请求成功，b站后端貌似没有验证UA。更新到最新代码就可以解决这个问题了
