### ISSUE TITLE
账户失效

### ISSUE THREAD

**Issue by luojian1996** [srcrs/BilibiliTask#55]
账户已失效，请在Secrets重新绑定你的信息。总是这个了

**Comment by srcrs** [comment]
> 账户已失效，请在Secrets重新绑定你的信息。总是这个了

触发风控了，我正在想解决办法，尝试伪造一个user- agent。

**Comment by menghuanali** [comment]
加油 我也是这个报错 这个太好用了 不想失去

**Comment by srcrs** [comment]
> 账户已失效，请在Secrets重新绑定你的信息。总是这个了

更新到最新代码即可解决

**Comment by srcrs** [comment]
> 加油 我也是这个报错 这个太好用了 不想失去

更新到最新代码即可解决

**Comment by windorz9** [comment]
> > 加油 我也是这个报错 这个太好用了 不想失去
> 
> 更新到最新代码即可解决

我昨天晚上更新了, 还是报这个错, 账户已失效, 我以为是饼干过期了, 又重新填一遍还是这样子. orz

**Comment by srcrs** [comment]
> > > 加油 我也是这个报错 这个太好用了 不想失去
> > 
> > 
> > 更新到最新代码即可解决
> 
> 我昨天晚上更新了, 还是报这个错, 账户已失效, 我以为是饼干过期了, 又重新填一遍还是这样子. orz

一会10:30再看一下吧，这个也很蹊跷，我后台设置的是80次尝试去执行，应该会在此之内访问成功，我在本地一般10次内就会有一次访问成功。

**Comment by lqrqw** [comment]
今天早上显示成功了。尝试登录次数：32

**Comment by srcrs** [comment]
> 今天早上显示成功了。尝试登录次数：32

这有点慢了

**Comment by Choicc** [comment]
> > 今天早上显示成功了。尝试登录次数：32
> 
> 这有点慢了

54次才成功

**Comment by ImSingee** [comment]
80 次尝试登录全部失败路过

**Comment by lqrqw** [comment]
可以抓自己手机真实的ua填进去么，这样会不会好点？

**Comment by blackwater996** [comment]
三天前失效了一次，重填解决了，今天重新填了三四次都救不了，估计是被封堵了。
大业未成，中道崩殂啊

**Comment by windorz9** [comment]
重新填写 4 个参数运行了 10 分钟跑起来了.
ps:之前跑失败全部都是运行了 20 多分钟. 然后一开始项目正常的时候都是跑 1 分多钟的.

**Comment by srcrs** [comment]
马上解决，已经知道问题所在了

**Comment by blackwater996** [comment]
中午自己投了五个币之后运行竟然正常了，奇妙

**Comment by windorz9** [comment]
> 马上解决，已经知道问题所在了
👍👍👍

**Comment by srcrs** [comment]
更新到最新代码试一试啊

**Comment by Choicc** [comment]
> 更新到最新代码试一试啊

已更新,没问题了。

**Comment by ImSingee** [comment]
@srcrs 看了代码改的地方我很懵，问题究竟出在哪里？难道是 Cookies 多了个分号……

**Comment by kistonw** [comment]
已更新到最新 还是账户失效

**Comment by Hello-Chen** [comment]
更新到最近代码，然后自己把cookie更新了，就可以了

> 已更新到最新 还是账户失效

更新到最近代码，然后自己把cookie更新了，就可以了

**Comment by Kevin6666666** [comment]
> > 账户已失效，请在保密重新绑定你的信息。总是这个了
> 
> 触发风控了，我正在想解决办法，尝试伪造一个user- agent。

请问现在修复了吗？
