### ISSUE TITLE
每日投币出现的问题

### ISSUE THREAD

**Issue by SoDebug** [srcrs/BilibiliTask#6]
第一次运行后发现每日投币没有生效，是需要什么额外出发条件吗

**Comment by srcrs** [comment]
不需要额外条件的。我看了一下你的actions日志，是有投币记录的，投了3个硬币。哔哩哔哩每日投币经验显示有时候会出现错误，你看一下你今天投了几个币就行了。

**Comment by SoDebug** [comment]
噢噢，好的
