### ISSUE TITLE
未设置优先投币UP主推送的信息显示投币异常

### ISSUE THREAD

**Issue by liub1934** [srcrs/BilibiliTask#81]
之前不是随机投币的吗，没配置的话应该随机投币的吧

**Comment by liub1934** [comment]
![image](https://user-images.githubusercontent.com/29849550/100825901-1a8a2f80-3494-11eb-9b7c-e2d997e2381c.png)

**Comment by srcrs** [comment]
> 之前不是随机投币的吗，没配置的话应该随机投币的吧

你再重新执行一下呢，这个可能是在获取视频的时候412 了

**Comment by liub1934** [comment]
明天自动执行的时候我再看看

**Comment by liub1934** [comment]
@srcrs 今天自动运行的时候还是报了上面的那个投币异常的错

**Comment by srcrs** [comment]
> @srcrs 今天自动运行的时候还是报了上面的那个投币异常的错

方便把你的cookie信息给我吗，我本地测一下什么原因。

**Comment by srcrs** [comment]
> @srcrs 今天自动运行的时候还是报了上面的那个投币异常的错

你用浏览器访问这个接口 https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?type_list=8 ，把获得的json信息给我

**Comment by liub1934** [comment]
> > @srcrs 今天自动运行的时候还是报了上面的那个投币异常的错
> 
> 方便把你的cookie信息给我吗，我本地测一下什么原因。

邮件发给你了

**Comment by zhongjf999** [comment]
怎么取消邮件提醒



在 2020-12-03 14:55:32，"srcrs" <notifications@github.com> 写道：

@srcrs 今天自动运行的时候还是报了上面的那个投币异常的错

你用浏览器访问这个接口 https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/dynamic_new?type_list=8 ，把获得的json信息给我

**Comment by srcrs** [comment]
![70deff14d61f6bc32c3f247c6632ee0](https://user-images.githubusercontent.com/49332985/100974969-3961f200-3578-11eb-8797-d06f4f3d56a4.png)

**Comment by zhongjf999** [comment]
怎么取消邮件提醒呢

**Comment by zhongjf999** [comment]
已退订，按照指引 绑定了微信，但没有推送消息

**Comment by srcrs** [comment]
> 已退订，按照指引 绑定了微信，但没有推送消息

填写了SCKEY吗

**Comment by zhongjf999** [comment]
![image](https://user-images.githubusercontent.com/75366022/100975402-f05e6d80-3578-11eb-9b4e-4d9e0d48bb2f.png)
是在这添加你的SCKey码吗

**Comment by srcrs** [comment]
嗯，填写你自己的SCKEY

**Comment by zhongjf999** [comment]
是新增存储库密码，格式什么的不需要什么模板吧？

**Comment by srcrs** [comment]
> 是新增存储库密码，格式什么的不需要什么模板吧？

![336555eb7a8a2d052d8dccde0d4e42a](https://user-images.githubusercontent.com/49332985/100975925-bc377c80-3579-11eb-89e2-1d3e7df39507.png)

**Comment by zhongjf999** [comment]
![image](https://user-images.githubusercontent.com/75366022/100975937-c0639a00-3579-11eb-8755-8b18d949f5f5.png)

**Comment by srcrs** [comment]
> > > @srcrs 今天自动运行的时候还是报了上面的那个投币异常的错
> > 
> > 
> > 方便把你的cookie信息给我吗，我本地测一下什么原因。
> 
> 邮件发给你了

你的号没有关注，所以没有最新动态，获取的接口数据跟我们不一样😂，我做一下处理吧。

**Comment by zhongjf999** [comment]
怎么设置优先给你投币来着，来个指引

**Comment by liub1934** [comment]
> 怎么设置优先给你投币来着，来个指引

大兄弟 你自己另开一个issue吧，这个我close掉了

**Comment by srcrs** [comment]
> 怎么设置优先给你投币来着，来个指引

```yml
upList:
  - 477137547
```

非常感谢😋

**Comment by srcrs** [comment]
> 之前不是随机投币的吗，没配置的话应该随机投币的吧

已经解决了，更新到最新代码吧
